version: "3.9"  # optional since v1.27.0
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8000"
    restart: always
    networks:
      - webnet

networks:
  webnet:
