apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-webapp
  labels:
    app: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: textutils
        image: textutils:1.0
        ports:
        - containerPort: 8000
